name:
  yaml_bot
description:
  A sample command-line application.
version:
  1.0.0
environment:
  sdk: ^3.7.2
dependencies:
  yaml: ^3.1.3
  yaml_edit: ^2.0.1
  http: ^0.13.0
  path: ^1.8.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.0.0
  http: ^0.13.0
